version: '3'

services:
  nginx-proxy:
    build: .
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - html:/etc/nginx/html:ro
      - conf:/etc/nginx/conf.d
      - certs:/etc/letsencrypt:rw
    network_mode: bridge

volumes:
  certs:
    driver: local
    driver_opts:
       type: none
       device: $PWD/certs
       o: bind
  conf:
    driver: local
    driver_opts:
      type: none
      device: $PWD/conf.d
      o: bind
  html:
    driver: local
    driver_opts:
      type: none
      device: $PWD/html
      o: bind